### ISSUE TITLE
Migrate from `react-infinite-calendar`

### ISSUE THREAD

**Issue by markerikson** [cypress-io/cypress-realworld-app#1556] opened 2024-06-25 03:44 UTC
While working on #1555 and trying out React 19, I also noticed a React error related to refs.

I've tracked it down to the `react-infinite-calendar` library, which A) hasn't been updated in 7 years, and B) is still using string refs, which have finally been removed in React 19.

You'll want to migrate away from that library to support React 19.

**Comment by MikeMcC399** [comment] 2024-06-25 08:22
- Duplicate of #1419

**Closed as not planned** 2024-06-25 13:53 UTC
Labels: duplicate
