### ISSUE TITLE
Mac M1 : Username or Password Invalid

### ISSUE THREAD

**Issue by SwathiVisagn123** [cypress-io/cypress-realworld-app#1326] opened 2023-04-12 15:50 UTC
Hi Team,

I know we have issues raised for errors on Macbook Pro M1. I wanted to mention I have below issues and need assistance please.

1. I have forked and cloned my forked repo.
2. yarn start gives me the following and it modifies my database.json once the application starts on my local server 3000.
<img width="1331" alt="Screenshot 2023-04-12 at 16 48 11" src="https://user-images.githubusercontent.com/113143886/231512680-3d252696-0678-42e7-8692-b61078507cee.png">

Username  Katharina_Bernier and password s3cret gives me an invalid error.

<img width="575" alt="Screenshot 2023-04-12 at 16 51 15" src="https://user-images.githubusercontent.com/113143886/231513077-455f2593-98af-4844-8c8b-c7874285e80b.png">

Can someone assist please

**Comment by faizvasaya** [comment] 2023-04-15 12:11
Hey @SwathiVisagn123 
I tried cloning the repository and logging in with the credentials you provided. Was able to log in successfully.

**Comment by SwathiVisagn123** [comment] 2023-04-17 12:03
@faizvasaya Thanks for checking this, may I know your OS and node version please

**Comment by SwathiVisagn123** [comment] 2023-04-17 12:04
I'm not sure how I can resolve my issue

**Comment by nagash77** [comment] 2023-04-21 13:37
Hi @SwathiVisagn123 I would suggest you check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

I was unable to reproduce your problem as well so I am going to close this issue until we can get a reproducible example.

**Closed as not planned by nagash77** 2023-04-21 13:37 UTC
